### ISSUE TITLE
Referencia a Keras en diapositiva de PyTorch

### ISSUE THREAD

**Issue by ptavaressilva** [JotaBlanco/TheValley#1]
En la presentación de la Clase 3 / Introducción a las redes neuronales, la diapositiva 68 (sobre PyTorch) indicas "Keras es una buena herramienta para entrenar redes neuronales personalizables y muy eficientes."

Creo que querías decir "PyTorch es una buena herramienta...", porque en la diapositiva anterior explicas las ventajas del uso de Keras.

No es grave, pero puede despistar si lo entiendes como "es mejor usar Keras".

**Comment by JotaBlanco** [comment]
Muchas gracias, @ptavaressilva!! Sí, era un error, así que muchas gracias por encontrarlo y comunicarlo. Acabo de corregirlo :)
